name: Publish Site

on: [push]
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: | 
          sudo apt install hugo pipx
          pip install rendercv
          ./build.sh

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs 

