name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Deps
        run: | 
          sudo apt install hugo pipx
          pip install rendercv

      - name: Deploy Site
        run: ./deploy.sh
